up sed

diff --git a/pass/luci-app-bypass/root/etc/init.d/bypass b/pass/luci-app-bypass/root/etc/init.d/bypass
--- a/pass/luci-app-bypass/root/etc/init.d/bypass
+++ b/pass/luci-app-bypass/root/etc/init.d/bypass
@@ -27,6 +27,8 @@ BIN_DIR=/usr/share/bypass
 DNS_FILE=/tmp/dnsmasq.d/dnsmasq-bypass.conf
 DNS_DIR=/tmp/dnsmasq.bypass
 O=$DNS_DIR/tmp
+ref=/tmp/resolv.conf.d/resolv.conf.auto;[ -s $ref ] || ref=/tmp/resolv.conf.auto
+REF=$(cat $ref 2>/dev/null | grep nameserver | awk '{print$2}')
 redir_tcp=0
 kcp_enable=0
 redir_udp=0
@@ -195,7 +197,7 @@ get_soip(){
 		if [ "$1" = 1 ];then
 			cat $LOG 2>/dev/null | sed -n '$p' | grep -q 'Check network status...' || gen_log
 			check_net
-			cat $LOG 2>/dev/null | sed -n '$p' | grep -q 'Check network status successful!' || log "By Rules     : Check network status successful!"
+			cat $LOG 2>/dev/null | sed -n '$p' | grep -q 'Check network status successful!' || log "Check network status successful!"
 		fi
 		socks5_ip=$(uci_get_by_name $SO_SERVER server)
 		if ! echo $socks5_ip | grep -E "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$">/dev/null;then
@@ -246,7 +248,7 @@ rules(){
 	fi
 	cat $LOG 2>/dev/null | sed -n '$p' | grep -q 'Check network status...\|Download IP/GFW files...' || gen_log
 	check_net
-	cat $LOG 2>/dev/null | sed -n '$p' | grep -q 'Download IP/GFW files...' || (log "By Rules     : Check network status successful!";log "By Rules     : Check IP/GFW files...")
+	cat $LOG 2>/dev/null | sed -n '$p' | grep -q 'Download IP/GFW files...' || (log "Check network status successful!";log "Check IP/GFW files...")
 	mkdir -p /var/run /var/etc
 	if [ ! -s $K/china.txt ] || [ $run_mode = router -a ! -s $K/china_v6.txt ] || ([ $run_mode = gfw -o $gfw_mode = 1 ] && [ ! -s $K/gfw.list ]);then
 		log "Download IP/GFW files..."
@@ -431,6 +433,7 @@ rules(){
 	[ $TG ] && TG="-J $tg_ip -K $tg_local_port"
 
 	get_soip
+	log " Get all server address successful!"
 	if [ "$lan_ac_ips" ];then
 		case $lan_ac_mode in
 			w|W|b|B)local ac_ips="$lan_ac_mode$lan_ac_ips";;
@@ -450,11 +453,11 @@ rules(){
 	r=1
 	while ! $BIN_DIR/rules -s "$server" -l "$local_port" -a "$ac_ips" -b "$(uci_get_by_type access_control wan_bp_ips)" -w "$(uci_get_by_type access_control wan_fw_ips)" \
 		-p "$(uci_get_by_type access_control lan_fp_ips)" -G "$(uci_get_by_type access_control lan_gm_ips)" -D "$proxyport" $mode $UDP $YB $NF $CU $TG $P $D;do
-		[ $r -ge 20 ] && log "By Rules     : Start iptables rules failed!" && return 1
+		[ $r -ge 20 ] && log "Start iptables rules failed!" && return 1
 		let r++;sleep 1
 	done
 	shunt_rules
-	log "By Rules     : Start iptables rules successful!"
+	log " Start iptables rules successful!"
 }
 
 start_tcp(){
@@ -868,8 +871,7 @@ gen_dns(){
 		[ ! "$dns_l" ] && log "SmartDNS      : Get Domestic DNS failed!" && return 1
 	fi
 	if [ "$dns_l" = isp ];then
-		ref=/tmp/resolv.conf.d/resolv.conf.auto;[ -s $ref ] || ref=/tmp/resolv.conf.auto
-		dns_l=$(cat $ref 2>/dev/null | grep nameserver | awk '{print$2}')
+		dns_l=$REF
 		[ ! "$dns_l" ] && log "SmartDNS      : Get Domestic DNS failed!" && return 1
 	fi
 	dns_l=$(echo $dns_l | sed -e 's/，/,/g' -e 's/。/./g' -e 's/：/:/g' -e 's/,/\n/g')
@@ -891,7 +893,7 @@ EOF
 	if [ $dns_mode = 0 ];then
 		echo $doh | sed 's/,/\n/g' | sed -e 's/^/server-https /g' -e 's/$/ -group a -exclude-default-group/g' >> $DNS_T
 		for i in $dns;do echo "server-tcp $i -group b -exclude-default-group" >> $DNS_T;done
-		echo -e "nameserver /dnsleaktest.com/b\nnameserver /whrq.net/b\nnameserver /speedtest.net/b\nnameserver /ooklaserver.net/b" >> $DNS_T
+		echo -e "nameserver /dnsleaktest.com/b\nnameserver /whrq.net/b\nnameserver /speedtest.net/b\nnameserver /ooklaserver.net/b\nnameserver /in-addr.arpa/b" >> $DNS_T
 		doh_t=$(echo $doh | sed 's/,/\n/g' | awk -F[/:] '{print$4}' | grep -Ev "^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$")
 		if [ "$doh_t" ];then
 			for i in $doh_t;do
@@ -903,7 +905,7 @@ EOF
 		fi
 	else
 		for i in $dns;do echo "server-tcp $i -group a -exclude-default-group" >> $DNS_T;done
-		echo -e "nameserver /dnsleaktest.com/a\nnameserver /whrq.net/a\nnameserver /speedtest.net/a\nnameserver /ooklaserver.net/a" >> $DNS_T
+		echo -e "nameserver /dnsleaktest.com/a\nnameserver /whrq.net/a\nnameserver /speedtest.net/a\nnameserver /ooklaserver.net/a\nnameserver /in-addr.arpa/a" >> $DNS_T
 	fi
 
 	if [ "$YB" ];then
@@ -1182,7 +1184,7 @@ EOF
 run_server(){
 	[ $(uci_get_by_name $1 enable 0) = 0 ] && return 1
 	let server_count=server_count+1
-	[ $server_count = 1 ] && iptables-save -t filter | grep BYBASS-S-RULE >/dev/null || iptables -N BYBASS-S-RULE && iptables -t filter -I INPUT -j BYBASS-S-RULE
+	[ $server_count = 1 ] && iptables-save -t filter | grep -q BYBASS-S-RULE || iptables -N BYBASS-S-RULE && iptables -I INPUT -j BYBASS-S-RULE
 	type=$(uci_get_by_name $1 type ssr)
 	[ $type = ss -o $type = ssr ] && cmd=$(f_bin $type-server) || cmd=$(which microsocks)
 	[ ! $cmd ] && log "By server    : Can't find $cmd program, start failed!" && return 1
@@ -1207,8 +1209,8 @@ run_server(){
 		$cmd -p $port $param $name >/dev/null 2>&1 &
 		log "By server    : Socks5 Server$server_count Started!";;
 	esac
-	iptables -t filter -A BYBASS-S-RULE -p tcp --dport $port -j ACCEPT
-	iptables -t filter -A BYBASS-S-RULE -p udp --dport $port -j ACCEPT
+	iptables -A BYBASS-S-RULE -p tcp --dport $port -j ACCEPT
+	iptables -A BYBASS-S-RULE -p udp --dport $port -j ACCEPT
 }
 
 gen_serv_include(){
@@ -1276,13 +1278,8 @@ stop(){
 	kill -9 $(ps -w | grep $VAR | grep -v grep | awk '{print$1}') 2>/dev/null
 	killall -q -9 smartdns-le chinadns-ng kcptun-client xray-plugin microsocks
 	$BIN_DIR/rules -f
-	srulecount=`iptables -nL | grep BYBASS-S-RULE | wc -l`
-	if [ $srulecount -gt 0 ];then
-		iptables -F BYBASS-S-RULE
-		iptables -t filter -D INPUT -j BYBASS-S-RULE
-		iptables -X BYBASS-S-RULE 2>/dev/null
-	fi
-	rm -rf $DNS_DIR $VAR*.json $DNS_FILE $CON_T /var/lock/bypass-update.lock $LOC_UCI
+	[ $(iptables -nL | grep BYBASS-S-RULE | wc -l) = 0 ] || (iptables -F BYBASS-S-RULE && iptables -X BYBASS-S-RULE;while iptables -D INPUT -j BYBASS-S-RULE 2>/dev/null;do :;done)
+	rm -rf $DNS_DIR $VAR*.json $DNS_FILE $CON_T /var/lock/overwall-update.lock $LOC_UCI
 	[ $run_mode = gfw -o $gfw_mode = 1 ] || rm -f $K/gfw.list
 	[ $run_mode = router ] || rm -f $K/china_v6.txt
 	[ ! $GLOBAL_SERVER ] && grep -q bypass $CRON_FILE && sed -i '/bypass/d' $CRON_FILE && /etc/init.d/cron restart
@@ -1299,27 +1296,9 @@ log-file $LOG
 bind :5335
 bind :5336
 bind :5337
+$([ $dns_mode_l = 0 ] && echo 223.5.5.5 223.6.6.6 | sed 's/ /\n/g' | sed 's/^/server /g' || echo $REF | sed 's/ /\n/g' | sed 's/^/server /g')
 EOF
-		if [ $dns_mode_l = 0 -a $(uci_get_by_type global isp_dns 0) = 0 ];then
-			dns_l="223.5.5.5 223.6.6.6"
-		else
-			dns_l=$(uci_get_by_type global udp_dns isp)
-		fi
-		if [ "$dns_l" = isp -o $dns_mode_l = 1 ];then
-			if [ "$dns_l" = isp ];then
-				ref=/tmp/resolv.conf.d/resolv.conf.auto;[ -s $ref ] || ref=/tmp/resolv.conf.auto
-				dns_l=$(cat $ref 2>/dev/null | grep nameserver | awk '{print$2}')
-			fi
-			if [ ! "$dns_l" ];then
-				log "SmartDNS      : Get Domestic DNS failed!"
-				exit 1
-			fi
-			dns_l=$(echo $dns_l | sed -e 's/，/,/g' -e 's/。/./g' -e 's/：/:/g' -e 's/,/\n/g')
-			for i in $dns_l;do echo "server $i" >> $DNS_T;done
-		else
-			for i in $dns_l;do echo "server-https https://$i/dns-query" >> $DNS_T;done
-		fi
-		$(which smartdns-le) -c $DNS_T
+		$(which smartdns) -c $DNS_T
 		r=1
 		while ! ps -w | grep smartdns-le | grep -qv grep;do
 			[ $r -ge 10 ] && return 1 || let r++
